---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/aditya1-1/aditya1-1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/283731/master/file/figures/aditya1-1/aditya1-1.png"
    folder_url: "/users/87737/articles/283731/master/folder/figures/aditya1-1"
